### ISSUE TITLE
should be possible to define guard function that takes parameters as with actions. 

### ISSUE THREAD

**Issue by gurgl** [stateless4j/stateless4j#28]
Feels like it should be possible to have paramtric guard functions as guards. Just as with the Dynamic transitions and Actions? Let the guard functions be Func<P1,...,PN,Boolean> ? And the parameter types determined by the TriggerWithParamaters...

**Comment by ahowardsky** [comment]
Have the same question, the guard function without taking in any parameters seems useless to me.
How could we pass in the required "Context" for it to determine whether the transition is allowed?

**Comment by CarstenEnglert** [comment]
Since I had the same requirement, I created a fork which introduces a single context parameter for the guardFunctions as well as the stateAccessor and stateMutator.
Check it out if you like: [@CarstenEnglert/stateless4j abfa44f](https://github.com/CarstenEnglert/stateless4j/commit/abfa44fb6099502a150608b6fddab0dd3f94714f)

As you can see, there are quite a few changes involved and I dropped the support of an initialState, as it doesn't make sense in a re-usable/contextual StateMachine/Configuration. Besides that, most of the API needed to be changed in order to allow the context parameter to be available.

Fyi:
* With those changes, the issues #19 and #37 are fully covered (for me) as well.
* I also reduced the publicFire log level from INFO to DEBUG (as mentioned in issue 40).
* Due to the breaking/incompatible changes, the mentioned fork produces the version 3.0 instead of 2.5.

**Comment by eugene-zolotko** [comment]
Hi everyone. I have the same need as @gurgl - to be able to evaluate trigger parameters within the guard function. Saw similar requests for the .NET stateless implementation: [https://github.com/dotnet-state-machine/stateless/issues/43](url) and [https://github.com/dotnet-state-machine/stateless/issues/155](url).

So I decided to implement and propose my solution (for Java only): [https://github.com/eugene-zolotko/stateless4j/commit/cb83637d92c15c6ab3ef4f666b4ec048e402b471](url).
I've added overloaded permitIf() and ignoreId() that take triggers with parameters and accept parametrized guards. The only problematic place in this solution is StateMachine.getPermittedTriggers() - there is no way to precisely list permitted triggers without evaluating their concrete params. Plus I haven't extended unit tests yet to cover the solution.

@oxo42 , Could you please take a look at this solution? Do you have some ideas how to properly change the getPermittedTriggers() behavior? What's your overall opinion? Is there any chances to get this solution pulled into your repository (of course after I'll extend unit tests)?

**Comment by ezaquarii** [comment]
.NET stateless didn't implement this feature and I it looks for me like the architecture is not ready to do it without significant compatibility breakage.

If I had to need to evaluate a guard using the argument value, I'd make this value part of the state somehow.
